---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-ex-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "12"

spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
