---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-cluster-amazon-eks-cluster-policy
  annotations:
    argocd.argoproj.io/sync-wave: "13"

spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    role: eks-ex-cluster-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy