---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-main
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1
    enableDnsHostnames: true
    enableDnsSupport: true
