---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: private-subnet-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    availabilityZone: us-east-1a
    region: us-east-1
    tags:
      kubernetes.io/role/internal-elb: "1"

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-2
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: private-subnet-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    availabilityZone: us-east-1b
    region: us-east-1
    tags:
      kubernetes.io/role/internal-elb: "1"

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: public-subnet-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    availabilityZone: us-east-1a
    region: us-east-1
    tags:
      kubernetes.io/role/elb: "1"

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-2
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: public-subnet-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    availabilityZone: us-east-1b
    region: us-east-1
    tags:
      kubernetes.io/role/elb: "1"
