---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  name: eip
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  label:
    name: eip
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1
    vpc: true

