
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: natgw
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    name: natgw
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    tags:
      Name: natgw
    region: us-east-1
    connectivityType: public
