---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: route-private
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: route-private

spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    region: us-east-1

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: route-public
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: route-public
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    region: us-east-1

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-1
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: private-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-2
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: private-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: public-1
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: public-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: public-2
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    name: public-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1
