apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 3-vpc.yaml
- 4-igw.yaml
- 5-subnet.yaml
- 6-EIP.yaml
- 7-nat.yaml
- 8-route-table.yaml
- 9-route.yaml
# - 12-eks-iam-role.yaml
# - 13-eks-iam-role-attachment.yaml
# - 15-nodes-iam-role.yaml
# - 16-nodes-iam-role-attachment.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  test: "1111"

commonLabels:
  project: sd4841