apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-dev
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: dev-sd4841-project
  source:
    path: application/provider
    repoURL: https://github.com/letrung910/sd4841_crossplane.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true