apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: dev-sd4841-project
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.14.5
    helm:
      releaseName: crossplane
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated:  # Automatically sync the application if new changes are detected
      prune: true  # Enables deletion of resources that are no longer in the repository
      selfHeal: true  # Enables self-healing to correct drifts from the desired state

    syncOptions:
    - CreateNamespace=true