---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: general
  annotations:
    argocd.argoproj.io/sync-wave: "17"

spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    clusterNameRef:
      name: dev-eks-created-by-crossplane
    nodeRoleArnRef:
      name: ex-eks-nodes-role
    region: us-east-1
    capacityType: ON_DEMAND
    instanceTypes: ["t3.small"]
    labels:
      role: general
    scalingConfig:
      - desiredSize: 1
        minSize: 1
        maxSize: 2
    subnetIdRefs:
      - name: dev-private-subnet-1
      - name: dev-private-subnet-2
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: spot
  annotations:
    argocd.argoproj.io/sync-wave: "17"

spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    clusterNameRef:
      name: dev-eks-created-by-crossplane
    nodeRoleArnRef:
      name: ex-eks-nodes-role
    region: us-east-1
    capacityType: SPOT
    instanceTypes: ["t3.small"]
    labels:
      role: spot
    taint:
      - key: type
        value: spot
        effect: NO_SCHEDULE
    scalingConfig:
      - desiredSize: 1
        minSize: 1
        maxSize: 2
    subnetIdRefs:
      - name: dev-private-subnet-1
      - name: dev-private-subnet-2