---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: igw
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: igw
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    region: us-east-1
    tags:
      Name: igw
    vpcIdSelector:
      matchLabels:
        name: vpc-main
        project: sd4841
        environment: dev