---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: private-subnet-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    cidrBlock: 10.0.0.0/19
    tags:
      Name: private-subnet-1
      kubernetes.io/cluster/dev-demo: "owned"
    vpcIdSelector:
      matchLabels:
        name: vpc-main
        project: sd4841
        environment: dev

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-2
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: private-subnet-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    cidrBlock: 10.0.32.0/19
    tags:
      Name: private-subnet-2
      kubernetes.io/cluster/dev-demo: "owned"
    vpcIdSelector:
      matchLabels:
        name: vpc-main
        project: sd4841
        environment: dev
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: public-subnet-1
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    cidrBlock: 10.0.64.0/19
    tags:
      Name: public-subnet-1
      kubernetes.io/cluster/dev-demo: "owned"
    vpcIdSelector:
      matchLabels:
        name: vpc-main
        project: sd4841
        environment: dev
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-2
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: public-subnet-2
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    cidrBlock: 10.0.96.0/19
    tags:
      Name: public-subnet-2
      kubernetes.io/cluster/dev-demo: "owned"
    vpcIdSelector:
      matchLabels:
        name: vpc-main
        project: sd4841
        environment: dev