
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: natgw
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  providerConfigRef:
    name: aws-provider  # This line points to your specific ProviderConfig
  forProvider:
    allocationIdSelector:
      matchLabels:
        project: sd4841
        name: eip
    subnetIdSelector:
      matchLabels:
        name: public-subnet-1
        project: sd4841
        environment: dev
