apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cidr-wildcard-mask
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    policies.kyverno.io/title: require-cidr-wildcard-mask
    policies.kyverno.io/description: >-
      Require wildcard mask for cidrBlock equal 16.
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: require-cidr-wildcard-mask
    match:
      any:
      - resources:
          kinds:
          - VPC
    validate:
      message: "CIDR Wildcard Mask must be equal 16."
      pattern:
        spec:
          forProvider:
            cidrBlock: "*16"
