apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: aks-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    name: aks-crossplane
spec:
  providerConfigRef:
    name: azure-provider
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        vnetSubnetId: /subscriptions/08ee43e5-09b4-41b0-ba99-0d04d8981913/resourceGroups/dev-crossplane-rg-aks/providers/Microsoft.Network/virtualNetworks/dev-vn-crossplane/subnets/dev-sub-crossplane
        # vnetSubnetIdSelector:
        #   matchLabels:
        #     name: sub-crossplane
        #     project: sd4841
        #     environment: dev
    dnsPrefix: aks
    identity:
      - type: SystemAssigned
    location: Central US
    resourceGroupNameSelector:
      matchLabels:
        name: crossplane-rg-aks
        project: sd4841
        environment: dev

