apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sub-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: sub-crossplane
spec:
  providerConfigRef:
    name: azure-provider
