apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: aks-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    name: aks-crossplane
spec:
  providerConfigRef:
    name: azure-provider

