apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 2-resource-group.yaml
- 4-virtual-network.yaml
- 5-subnet.yaml
- 7-aks.yaml




commonAnnotations:
  argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"


commonLabels:
  project: sd4841